const servicesData = [
  {
    category: {
      name: 'Electronic Repair Services',
      description:
        'Professional repair services for all types of electronic devices including mobile phones, TVs, desktops, gaming consoles, and smart home devices.',
      icon: '📱',
      featured: true,
      displayOrder: 1,
    },
    subServices: [
      // Mobile Repair Services
      {
        name: 'Mobile Screen Replacement',
        description: 'Professional screen replacement for all mobile brands with warranty',
        priceRange: { min: 1000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
        features: ['Genuine parts', 'Warranty included', 'Doorstep service'],
        popular: true,
      },
      {
        name: 'Mobile Battery Replacement',
        description: 'Replace worn-out batteries with high-quality replacements',
        priceRange: { min: 500, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
        features: ['Original battery', 'Warranty included', 'Quick service'],
      },
      {
        name: 'Charging Port Repair',
        description: 'Fix charging port issues and connectivity problems',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Speaker & Microphone Repair',
        description: 'Repair or replace faulty speakers and microphones',
        priceRange: { min: 200, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Mobile Camera Repair',
        description: 'Fix camera issues, replace faulty camera modules',
        priceRange: { min: 500, max: 2500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Water Damage Repair',
        description: 'Complete water damage diagnostics and repair',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Motherboard & Chip-Level Repair',
        description: 'Advanced motherboard and chip-level repairs',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'Network Issues Fix',
        description: 'Resolve network connectivity and signal problems',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Mobile Software Troubleshooting',
        description: 'Fix software issues, update OS, remove malware',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Data Recovery & Backup',
        description: 'Recover lost data and create secure backups',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      // TV Repair Services
      {
        name: 'LED/LCD/OLED Screen Replacement',
        description: 'Professional TV screen replacement for all brands',
        priceRange: { min: 5000, max: 30000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Expert technicians', 'Quality parts', 'Home service'],
        popular: true,
      },
      {
        name: 'TV Backlight Repair',
        description: 'Fix backlight issues, dim display problems',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'TV Power & Startup Issues Fix',
        description: 'Resolve power supply and startup problems',
        priceRange: { min: 500, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV Remote Sensor Repair',
        description: 'Fix remote sensor connectivity issues',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV Sound & Speaker Repair',
        description: 'Repair audio output and speaker problems',
        priceRange: { min: 500, max: 2500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV Software & Firmware Updates',
        description: 'Update TV software and firmware to latest version',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV WiFi & Internet Connectivity Issues',
        description: 'Fix smart TV connectivity problems',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV Motherboard & Chip-Level Repair',
        description: 'Advanced motherboard repairs for TVs',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'HDMI & Other Ports Repair',
        description: 'Repair or replace damaged HDMI and other ports',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'TV Color & Picture Quality Issues',
        description: 'Fix display color and picture quality problems',
        priceRange: { min: 500, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'TV Wall Mounting & Installation',
        description: 'Professional TV wall mounting service',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      // Desktop Repair Services
      {
        name: 'CPU & Motherboard Repair',
        description: 'Comprehensive CPU and motherboard diagnostics and repair',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'RAM & Hard Drive Upgrade/Replacement',
        description: 'Upgrade or replace RAM and storage devices',
        priceRange: { min: 1000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Power Supply Repair',
        description: 'Fix or replace faulty power supply units',
        priceRange: { min: 500, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Graphics Card Installation & Repair',
        description: 'Install or repair graphics cards for gaming/work',
        priceRange: { min: 1000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Monitor Repair',
        description: 'Repair display issues, dead pixels, power problems',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Keyboard & Mouse Issues Fix',
        description: 'Repair or replace faulty input devices',
        priceRange: { min: 200, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Cooling System Cleaning & Fan Replacement',
        description: 'Clean cooling system, replace fans, prevent overheating',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'OS Installation & System Formatting',
        description: 'Install operating system, format drives',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Desktop Networking & Internet Issues Fix',
        description: 'Resolve network connectivity problems',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Virus Removal & System Speed Optimization',
        description: 'Remove malware, optimize system performance',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      // Gaming Console Repair Services
      {
        name: 'PlayStation/Xbox/Nintendo Repair',
        description: 'Professional gaming console repair services',
        priceRange: { min: 1000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Expert technicians', 'Warranty included'],
      },
      {
        name: 'Controller Repair & Button Replacement',
        description: 'Fix controller buttons, joysticks, and connectivity',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Console Overheating Issues Fix',
        description: 'Resolve overheating problems in gaming consoles',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Console Software & Firmware Updates',
        description: 'Update console firmware and software',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Console HDMI Port & Power Issues Fix',
        description: 'Repair HDMI ports and power supply issues',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      // Smart Home & Other Electronics Repair
      {
        name: 'Home Theater & Speaker Repair',
        description: 'Repair home theater systems and speakers',
        priceRange: { min: 500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Set-Top Box & Streaming Device Repair',
        description: 'Fix streaming devices and set-top boxes',
        priceRange: { min: 300, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'CCTV Camera Installation & Repair',
        description: 'Install and repair CCTV security cameras',
        priceRange: { min: 500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Router & Modem Troubleshooting',
        description: 'Fix internet connectivity and router issues',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
    ],
  },
  {
    category: {
      name: 'Vehicle Repair Services',
      description:
        'Comprehensive vehicle repair services for bikes, cars, auto rickshaws, electric vehicles, and trucks. Includes roadside assistance and emergency repairs.',
      icon: '🚗',
      featured: true,
      displayOrder: 2,
    },
    subServices: [
      // Bike Repairs
      {
        name: 'Bike Engine Repair & Tuning',
        description: 'Complete engine diagnostics, repair and tuning',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
        features: ['Expert mechanics', 'Doorstep service', 'Quality parts'],
        popular: true,
      },
      {
        name: 'Bike Clutch Plate Replacement',
        description: 'Replace worn clutch plates',
        priceRange: { min: 800, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Bike Brake Repair & Replacement',
        description: 'Brake system repair and part replacement',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Bike Battery Replacement & Charging',
        description: 'Battery replacement and charging services',
        priceRange: { min: 800, max: 2500 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Bike Tyre Puncture Repair & Replacement',
        description: 'Quick tyre puncture repair and replacement',
        priceRange: { min: 50, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
        popular: true,
      },
      {
        name: 'Chain & Sprocket Replacement',
        description: 'Replace worn chain and sprocket',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Carburetor Cleaning & Tuning',
        description: 'Clean and tune carburetor for better performance',
        priceRange: { min: 300, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Fuel Injector Cleaning',
        description: 'Professional fuel injector cleaning service',
        priceRange: { min: 500, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Bike Oil Change & Filter Replacement',
        description: 'Engine oil change and filter replacement',
        priceRange: { min: 500, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Bike Suspension Repair',
        description: 'Front fork and shock absorber repair',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Handlebar & Steering Alignment',
        description: 'Align handlebar and steering system',
        priceRange: { min: 200, max: 500 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Bike Electrical Wiring & Lighting Repair',
        description: 'Fix electrical issues and lighting problems',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Exhaust System Repair & Silencer Replacement',
        description: 'Repair exhaust and replace silencer',
        priceRange: { min: 500, max: 2500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Bike Cooling System Repair',
        description: 'Radiator repair and coolant replacement',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      // Car Repairs
      {
        name: 'Car Engine Diagnostics & Repair',
        description: 'Comprehensive engine diagnostics and repair',
        priceRange: { min: 1000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
        features: ['Advanced diagnostics', 'Expert mechanics', 'Home service'],
        popular: true,
      },
      {
        name: 'Transmission & Gearbox Repair',
        description: 'Transmission and gearbox repair services',
        priceRange: { min: 5000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Car Brake System Repair & Fluid Change',
        description: 'Complete brake system service',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Car Suspension & Shock Absorber Repair',
        description: 'Suspension system repair and maintenance',
        priceRange: { min: 2000, max: 6000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'Wheel Alignment & Balancing',
        description: 'Professional wheel alignment and balancing',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Car Tyre Puncture & Replacement',
        description: 'Tyre repair and replacement services',
        priceRange: { min: 50, max: 15000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
        popular: true,
      },
      {
        name: 'Car Battery Replacement & Charging',
        description: 'Battery replacement and charging services',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Car AC Repair & Gas Refilling',
        description: 'AC repair and gas refilling services',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Car Fuel System Cleaning',
        description: 'Fuel injectors and fuel pump cleaning',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Car Oil & Filter Change',
        description: 'Engine oil and filter replacement',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Car Clutch Repair & Replacement',
        description: 'Clutch system repair and replacement',
        priceRange: { min: 2000, max: 8000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
      },
      {
        name: 'Exhaust & Emission System Repair',
        description: 'Exhaust and emission control repair',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Car Steering System Repair',
        description: 'Power steering and steering system repair',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'Car Electrical Wiring & Lighting Repair',
        description: 'Electrical system and lighting repair',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Car Body Denting & Painting',
        description: 'Professional denting and painting services',
        priceRange: { min: 5000, max: 50000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      // Auto Rickshaw Repairs
      {
        name: 'Auto Rickshaw Engine Repair & Tuning',
        description: 'Engine repair and tuning for auto rickshaws',
        priceRange: { min: 800, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Auto Clutch & Gear Repair',
        description: 'Clutch and gear system repair',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Auto Brake Repair & Replacement',
        description: 'Brake system repair for auto rickshaws',
        priceRange: { min: 300, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Auto Electrical System Repair',
        description: 'Battery, wiring, and lights repair',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Auto Tyre Puncture Repair & Replacement',
        description: 'Tyre services for auto rickshaws',
        priceRange: { min: 50, max: 3500 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Auto Fuel Injector & Carburetor Cleaning',
        description: 'Fuel system cleaning for auto rickshaws',
        priceRange: { min: 300, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Auto Suspension & Shock Absorber Repair',
        description: 'Suspension system repair',
        priceRange: { min: 800, max: 2500 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Auto Oil Change & Lubrication',
        description: 'Engine oil change and lubrication',
        priceRange: { min: 300, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Auto Exhaust System Repair',
        description: 'Exhaust system repair',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      // Electric Vehicle Repairs
      {
        name: 'EV Battery Diagnostics & Replacement',
        description: 'Battery health check and replacement',
        priceRange: { min: 5000, max: 50000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
        features: ['Expert EV technicians', 'Certified parts'],
        popular: true,
      },
      {
        name: 'EV Motor Repair & Servicing',
        description: 'Electric motor repair and maintenance',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'EV Controller & Wiring Repairs',
        description: 'Controller and electrical wiring repairs',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'EV Brake System Repair & Maintenance',
        description: 'Brake system service for electric vehicles',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'EV Tyre & Wheel Alignment',
        description: 'Tyre and wheel alignment services',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'EV Suspension System Repair',
        description: 'Suspension repair for electric vehicles',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'EV Software & Firmware Updates',
        description: 'Update vehicle software and firmware',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'EV Charging Port & Charger Repair',
        description: 'Charging port and charger repair',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'EV Display Panel & Dashboard Repairs',
        description: 'Dashboard and display panel repairs',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'EV Cooling System Repair',
        description: 'Battery cooling system repair',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      // Lorry & Truck Repairs
      {
        name: 'Truck Engine Overhauling & Tuning',
        description: 'Complete engine overhaul for trucks',
        priceRange: { min: 10000, max: 50000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Truck Gearbox & Clutch Repair',
        description: 'Gearbox and clutch repair for heavy vehicles',
        priceRange: { min: 5000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Truck Brake System Repair',
        description: 'Air and hydraulic brake system repair',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
      },
      {
        name: 'Truck Suspension & Chassis Repair',
        description: 'Suspension and chassis repair',
        priceRange: { min: 3000, max: 15000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Truck Tyre Puncture & Replacement',
        description: 'Heavy vehicle tyre services',
        priceRange: { min: 50, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Truck Battery Charging & Replacement',
        description: 'Heavy duty battery services',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Truck Fuel System Repair',
        description: 'Fuel injectors and pump repair',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
      },
      {
        name: 'Truck Exhaust System & Emission Control',
        description: 'Exhaust and emission system repair',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'hours' },
      },
      {
        name: 'Truck Steering System Alignment',
        description: 'Steering alignment for heavy vehicles',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Truck Cooling System Repair',
        description: 'Radiator and coolant system repair',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'range',
        estimatedDuration: { value: 4, unit: 'hours' },
      },
      {
        name: 'Truck Body Welding & Denting',
        description: 'Body repair and welding services',
        priceRange: { min: 5000, max: 50000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Hydraulic System Repairs',
        description: 'Hydraulic system repair for dump trucks and cranes',
        priceRange: { min: 5000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      // Highway Breakdown & Emergency Repairs
      {
        name: 'Jump-Start Service',
        description: 'Emergency jump-start for dead batteries',
        priceRange: { min: 200, max: 500 },
        priceType: 'fixed',
        estimatedDuration: { value: 30, unit: 'minutes' },
        features: ['24/7 service', 'Quick response'],
        popular: true,
      },
      {
        name: 'Emergency Tyre Service',
        description: 'Roadside tyre repair and replacement',
        priceRange: { min: 50, max: 15000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
        popular: true,
      },
      {
        name: 'Emergency Fuel Delivery',
        description: 'Fuel delivery service on highways',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'On-the-Spot Minor Repairs',
        description: 'Quick roadside repairs for emergencies',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Vehicle Towing Service',
        description: 'Professional towing for non-working vehicles',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Emergency Oil & Coolant Refill',
        description: 'Roadside oil and coolant refill',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
      {
        name: 'Alternator & Starter Motor Repairs',
        description: 'Emergency alternator and starter repairs',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Emergency Headlight & Electrical Fixes',
        description: 'Quick electrical system fixes',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 30, unit: 'minutes' },
      },
    ],
  },
  {
    category: {
      name: 'Kitchen Repair Services',
      description:
        'Professional repair and installation services for all kitchen appliances including mixers, cookers, microwaves, refrigerators, and more.',
      icon: '🍳',
      featured: true,
      displayOrder: 3,
    },
    subServices: [
      {
        name: 'Mixer Repair',
        description: 'Repair mixers, grinders, and blenders',
        priceRange: { min: 200, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
        features: ['Doorstep service', 'Quality parts'],
      },
      {
        name: 'Cooker Repair',
        description: 'Pressure cooker and induction cooker repair',
        priceRange: { min: 200, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Microwave Oven Repair',
        description: 'Microwave oven repair and servicing',
        priceRange: { min: 800, max: 3500 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
        popular: true,
      },
      {
        name: 'Refrigerator Repair',
        description: 'Fridge and freezer repair services',
        priceRange: { min: 500, max: 6000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
        popular: true,
      },
      {
        name: 'Dishwasher Repair',
        description: 'Dishwasher repair and maintenance',
        priceRange: { min: 500, max: 3500 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Water Purifier Repair',
        description: 'RO and water purifier repair',
        priceRange: { min: 200, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Toaster Repair',
        description: 'Toaster and sandwich maker repair',
        priceRange: { min: 200, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Electric Kettle Repair',
        description: 'Electric kettle repair services',
        priceRange: { min: 200, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Blender Repair',
        description: 'Hand blender and mixer repair',
        priceRange: { min: 200, max: 1500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
    ],
  },
  {
    category: {
      name: 'Motor Repair Services',
      description:
        'Industrial and household motor repair services including rewinding, pump repairs, transformer servicing, and more.',
      icon: '⚙️',
      featured: false,
      displayOrder: 4,
    },
    subServices: [
      {
        name: 'AC Motor Rewinding Service',
        description: 'Professional AC motor rewinding',
        priceRange: { min: 2000, max: 4500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'LT Motor Rewinding Service',
        description: 'Low tension motor rewinding',
        priceRange: { min: 2500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Heavy Duty Motor Rewinding',
        description: 'Heavy duty industrial motor rewinding',
        priceRange: { min: 5000, max: 15000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Generator Stator and Rotor Rewinding',
        description: 'Generator rewinding services',
        priceRange: { min: 50000, max: 150000 },
        priceType: 'range',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Large Capacity Stator Rewinding',
        description: 'Large capacity motor stator rewinding',
        priceRange: { min: 200000, max: 500000 },
        priceType: 'range',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Servo Motor Rewinding',
        description: 'Servo motor rewinding and repair',
        priceRange: { min: 5000, max: 50000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Pump Motor Repair',
        description: 'Water pump motor repair and rewinding',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'days' },
        popular: true,
      },
      {
        name: 'Electric Motor Bearing Replacement',
        description: 'Motor bearing replacement service',
        priceRange: { min: 500, max: 2000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Electric Motor Complex Repairs',
        description: 'Complex motor repairs and rewinding',
        priceRange: { min: 5000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Transformer Repair & Rewinding',
        description: 'Transformer repair and rewinding services',
        priceRange: { min: 10000, max: 100000 },
        priceType: 'range',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Welding Machine Repair',
        description: 'Welding machine repair and rewinding',
        priceRange: { min: 5000, max: 20000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Motor Lubrication and Cleaning',
        description: 'Motor maintenance and cleaning',
        priceRange: { min: 100, max: 500 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Motor Filter Replacement',
        description: 'Replace motor filters',
        priceRange: { min: 200, max: 1000 },
        priceType: 'range',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Motor Electrical Component Replacement',
        description: 'Replace electrical components in motors',
        priceRange: { min: 500, max: 5000 },
        priceType: 'range',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
    ],
  },
  {
    category: {
      name: 'Laundry Services',
      description:
        'On-demand laundry services including washing, dry cleaning, ironing, and fabric care with doorstep pickup and delivery.',
      icon: '👔',
      featured: true,
      displayOrder: 5,
    },
    subServices: [
      {
        name: 'Regular Wash',
        description: 'Machine wash with detergent and softener',
        priceRange: { min: 59, max: 79 },
        priceType: 'per-item',
        estimatedDuration: { value: 24, unit: 'hours' },
        features: ['Pickup & delivery', 'Quality detergents', 'Minimum ₹399'],
        popular: true,
      },
      {
        name: 'Premium Wash',
        description: 'Deep cleaning with fabric care solutions',
        priceRange: { min: 89, max: 149 },
        priceType: 'per-item',
        estimatedDuration: { value: 24, unit: 'hours' },
        features: ['Premium care', 'Fabric softener', 'Minimum ₹600'],
      },
      {
        name: 'Hand Wash',
        description: 'Gentle hand wash for delicate fabrics',
        priceRange: { min: 100, max: 200 },
        priceType: 'per-item',
        estimatedDuration: { value: 24, unit: 'hours' },
        features: ['Delicate care', 'Expert handling', 'Minimum ₹800'],
      },
      {
        name: 'Dry Cleaning',
        description: 'Chemical-based cleaning for special garments',
        priceRange: { min: 59, max: 250 },
        priceType: 'per-item',
        estimatedDuration: { value: 48, unit: 'hours' },
        features: ['Professional cleaning', 'Stain removal', 'Minimum ₹200'],
        popular: true,
      },
      {
        name: 'Ironing Service',
        description: 'Professional ironing and pressing',
        priceRange: { min: 10, max: 50 },
        priceType: 'per-item',
        estimatedDuration: { value: 12, unit: 'hours' },
        features: ['Steam ironing', 'Crease removal'],
      },
    ],
  },
  {
    category: {
      name: 'Tailoring Services',
      description:
        'Professional tailoring services including custom stitching, alterations, embroidery, and design work for men, women, and kids.',
      icon: '✂️',
      featured: true,
      displayOrder: 6,
    },
    subServices: [
      // Custom Stitching
      {
        name: 'Custom Dress Stitching',
        description: 'Tailor-made dresses and outfits',
        priceRange: { min: 800, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
        features: ['Home visit for measurement', 'Custom fitting'],
      },
      {
        name: 'Suits Stitching',
        description: 'Custom suits tailoring',
        priceRange: { min: 1500, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Ethnic Wear Stitching',
        description: 'Traditional ethnic wear tailoring',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
        popular: true,
      },
      {
        name: 'Formal Shirts Stitching',
        description: 'Custom formal shirt tailoring',
        priceRange: { min: 1000, max: 2500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Casual Wear Stitching',
        description: 'Casual outfits and t-shirt stitching',
        priceRange: { min: 500, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Kids Clothing Stitching',
        description: 'Custom kids wear tailoring',
        priceRange: { min: 500, max: 3000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Uniform Stitching',
        description: 'School, office, and industrial uniforms',
        priceRange: { min: 800, max: 3500 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      // Alteration & Repair Services
      {
        name: 'Size Adjustments',
        description: 'Tightening, loosening, and fitting adjustments',
        priceRange: { min: 100, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
        popular: true,
      },
      {
        name: 'Length Adjustments',
        description: 'Shortening and lengthening services',
        priceRange: { min: 100, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Zip, Button & Hook Replacement',
        description: 'Replace faulty zips, buttons, and hooks',
        priceRange: { min: 50, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Patchwork and Tear Repair',
        description: 'Repair tears and add patches',
        priceRange: { min: 100, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      // Women's Wear Tailoring
      {
        name: 'Blouse Stitching',
        description: 'Custom blouse tailoring',
        priceRange: { min: 590, max: 1490 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
        popular: true,
      },
      {
        name: 'Lehenga Stitching',
        description: 'Custom lehenga tailoring',
        priceRange: { min: 1490, max: 12000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Saree Fall Stitching',
        description: 'Saree fall and pico services',
        priceRange: { min: 100, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Kurti Stitching',
        description: 'Custom kurti tailoring',
        priceRange: { min: 580, max: 780 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Salwar Suit Stitching',
        description: 'Salwar kameez tailoring',
        priceRange: { min: 849, max: 1549 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Anarkali Stitching',
        description: 'Custom anarkali suit tailoring',
        priceRange: { min: 1580, max: 2490 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Gown Stitching',
        description: 'Custom gown tailoring',
        priceRange: { min: 7500, max: 15000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Women Party Wear Customization',
        description: 'Party wear outfit tailoring',
        priceRange: { min: 2000, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Skirts Stitching',
        description: 'Custom skirt tailoring',
        priceRange: { min: 1090, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Women Pants Stitching',
        description: 'Custom pants and trousers',
        priceRange: { min: 849, max: 1549 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Jumpsuit Stitching',
        description: 'Custom jumpsuit tailoring',
        priceRange: { min: 2490, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      // Men's Wear Tailoring
      {
        name: 'Men Shirt Stitching',
        description: 'Custom shirt tailoring for men',
        priceRange: { min: 1850, max: 3500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Men Trousers Stitching',
        description: 'Custom trousers tailoring',
        priceRange: { min: 2000, max: 3500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Blazer Stitching',
        description: 'Custom blazer tailoring',
        priceRange: { min: 7000, max: 20000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
        popular: true,
      },
      {
        name: 'Kurta Stitching',
        description: 'Men kurta tailoring',
        priceRange: { min: 2000, max: 3500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Sherwani Stitching',
        description: 'Custom sherwani for weddings',
        priceRange: { min: 18000, max: 28000 },
        priceType: 'per-item',
        estimatedDuration: { value: 15, unit: 'days' },
      },
      {
        name: 'Men Wedding Wear',
        description: 'Custom wedding outfit tailoring',
        priceRange: { min: 10000, max: 50000 },
        priceType: 'per-item',
        estimatedDuration: { value: 20, unit: 'days' },
      },
      {
        name: 'T-shirt & Jeans Alteration',
        description: 'Alter and fit t-shirts and jeans',
        priceRange: { min: 100, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Waistcoat Stitching',
        description: 'Custom waistcoat tailoring',
        priceRange: { min: 4500, max: 10000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Jacket Stitching',
        description: 'Custom jacket tailoring',
        priceRange: { min: 7000, max: 20000 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      // Kids Wear Tailoring
      {
        name: 'Kids Party Wear',
        description: 'Party and festive wear for kids',
        priceRange: { min: 1000, max: 3000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Kids Casual Outfits',
        description: 'Casual clothing for kids',
        priceRange: { min: 500, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'School Uniform Stitching',
        description: 'School uniform tailoring',
        priceRange: { min: 800, max: 3500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Kids Traditional & Festival Wear',
        description: 'Traditional outfits for kids',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      // Home Furnishing Stitching
      {
        name: 'Curtain Stitching',
        description: 'Custom curtain tailoring',
        priceRange: { min: 500, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Bedsheet Stitching',
        description: 'Custom bedsheet tailoring',
        priceRange: { min: 200, max: 1000 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Sofa Cover Stitching',
        description: 'Custom sofa cover tailoring',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Cushion Cover Stitching',
        description: 'Custom cushion cover tailoring',
        priceRange: { min: 100, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Table Cloth Stitching',
        description: 'Custom table cloth tailoring',
        priceRange: { min: 200, max: 1000 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Upholstery Tailoring',
        description: 'Furniture upholstery services',
        priceRange: { min: 1000, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      // Embroidery & Custom Designs
      {
        name: 'Hand Embroidery',
        description: 'Traditional hand embroidery work',
        priceRange: { min: 100, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
        popular: true,
      },
      {
        name: 'Machine Embroidery',
        description: 'Precision machine embroidery',
        priceRange: { min: 100, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Personalized Name/Logo Embroidery',
        description: 'Custom name and logo embroidery',
        priceRange: { min: 200, max: 3000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Custom Prints & Fabric Painting',
        description: 'Fabric printing and painting services',
        priceRange: { min: 500, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      // Maggam Work & Traditional Embroidery
      {
        name: 'Simple Hand Embroidery Pattern',
        description: 'Simple embroidery patterns with beads',
        priceRange: { min: 100, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Intricate Hand Embroidery Design',
        description: 'Intricate designs with pearls and sequins',
        priceRange: { min: 1000, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Heavy Bridal Embroidery Work',
        description: 'Heavy embroidery for bridal wear',
        priceRange: { min: 7500, max: 10000 },
        priceType: 'per-item',
        estimatedDuration: { value: 15, unit: 'days' },
      },
      {
        name: 'Basic Machine Embroidery Design',
        description: 'Simple machine embroidery patterns',
        priceRange: { min: 250, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: '3D Machine Embroidery',
        description: '3D flower patterns and designs',
        priceRange: { min: 5000, max: 7000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Digitized Custom Embroidery Design',
        description: 'Custom digitized embroidery patterns',
        priceRange: { min: 250, max: 1000 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Basic Aari Work',
        description: 'Basic aari work with floral borders',
        priceRange: { min: 500, max: 1000 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Heavy Aari Work',
        description: 'Heavy aari work with beads and stones',
        priceRange: { min: 2000, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Light Zardozi Work',
        description: 'Light zardozi embroidery',
        priceRange: { min: 1500, max: 3000 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Heavy Zardozi Work',
        description: 'Heavy zardozi for bridal wear',
        priceRange: { min: 5000, max: 10000 },
        priceType: 'per-item',
        estimatedDuration: { value: 15, unit: 'days' },
      },
      {
        name: 'Simple Chikankari Embroidery',
        description: 'Light chikankari work on cotton',
        priceRange: { min: 100, max: 300 },
        priceType: 'per-item',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Heavy Chikankari Work',
        description: 'Intricate chikankari on georgette',
        priceRange: { min: 1000, max: 2000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Basic Mirror Work',
        description: 'Basic mirror work on patches',
        priceRange: { min: 200, max: 500 },
        priceType: 'per-item',
        estimatedDuration: { value: 3, unit: 'days' },
      },
      {
        name: 'Heavy Mirror Work',
        description: 'Heavy mirror work on full garments',
        priceRange: { min: 1500, max: 4000 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Basic Kashmiri Embroidery',
        description: 'Basic kashida work on shawls',
        priceRange: { min: 980, max: 3985 },
        priceType: 'per-item',
        estimatedDuration: { value: 10, unit: 'days' },
      },
      {
        name: 'Detailed Kashmiri Embroidery',
        description: 'Intricate kashida on woolen fabrics',
        priceRange: { min: 4000, max: 10000 },
        priceType: 'per-item',
        estimatedDuration: { value: 20, unit: 'days' },
      },
      {
        name: 'Light Phulkari Work',
        description: 'Light phulkari embroidery',
        priceRange: { min: 800, max: 1500 },
        priceType: 'per-item',
        estimatedDuration: { value: 7, unit: 'days' },
      },
      {
        name: 'Heavy Phulkari Bagh Work',
        description: 'Heavy phulkari bagh embroidery',
        priceRange: { min: 2500, max: 4500 },
        priceType: 'per-item',
        estimatedDuration: { value: 15, unit: 'days' },
      },
    ],
  },
  {
    category: {
      name: 'Interior & Construction Services',
      description:
        'Interior design, mini-construction, renovation services, and construction material delivery with real-time tracking.',
      icon: '🏠',
      featured: false,
      displayOrder: 7,
    },
    subServices: [
      {
        name: 'Interior Design Consultation',
        description: 'Professional interior design consultation',
        priceRange: { min: 5000, max: 50000 },
        priceType: 'custom',
        estimatedDuration: { value: 3, unit: 'days' },
        features: ['Expert designers', '3D visualization', 'Budget planning'],
      },
      {
        name: 'Furniture Layout & Space Planning',
        description: 'Optimize space with furniture planning',
        priceRange: { min: 3000, max: 20000 },
        priceType: 'custom',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Color Selection & Painting',
        description: 'Color consultation and painting services',
        priceRange: { min: 5000, max: 100000 },
        priceType: 'custom',
        estimatedDuration: { value: 5, unit: 'days' },
      },
      {
        name: 'Lighting Design & Installation',
        description: 'Lighting design and installation',
        priceRange: { min: 2000, max: 50000 },
        priceType: 'custom',
        estimatedDuration: { value: 2, unit: 'days' },
      },
      {
        name: 'Tiling Services',
        description: 'Floor and wall tiling services',
        priceRange: { min: 10000, max: 200000 },
        priceType: 'custom',
        estimatedDuration: { value: 7, unit: 'days' },
        popular: true,
      },
      {
        name: 'Plumbing Services',
        description: 'Plumbing installation and repair',
        priceRange: { min: 500, max: 50000 },
        priceType: 'custom',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Fixture Installation',
        description: 'Install bathroom and kitchen fixtures',
        priceRange: { min: 500, max: 20000 },
        priceType: 'custom',
        estimatedDuration: { value: 1, unit: 'days' },
      },
      {
        name: 'Construction Material Delivery',
        description: 'Cement, bricks, rods delivery with tracking',
        priceRange: { min: 1000, max: 500000 },
        priceType: 'custom',
        estimatedDuration: { value: 1, unit: 'days' },
        features: ['Real-time tracking', 'Quality materials', 'Bulk orders'],
        popular: true,
      },
    ],
  },
  {
    category: {
      name: 'Educational & Business Support',
      description:
        'Student transport services, printing, xerox, lamination, binding, and document services with home delivery.',
      icon: '📚',
      featured: false,
      displayOrder: 8,
    },
    subServices: [
      {
        name: 'Student Dropping Service',
        description: 'Safe transport for students to schools and colleges',
        priceRange: { min: 2000, max: 10000 },
        priceType: 'custom',
        estimatedDuration: { value: 1, unit: 'hours' },
        features: ['Safe travel', 'Verified drivers', 'Real-time tracking'],
      },
      {
        name: 'Xerox & Printing Service',
        description: 'Document xerox and printing with home delivery',
        priceRange: { min: 1, max: 10 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Color & B/W', 'Home delivery', 'Bulk orders'],
        popular: true,
      },
      {
        name: 'Lamination Service',
        description: 'Document lamination at home',
        priceRange: { min: 10, max: 50 },
        priceType: 'per-item',
        estimatedDuration: { value: 1, unit: 'hours' },
      },
      {
        name: 'Binding Service',
        description: 'Document binding services',
        priceRange: { min: 20, max: 200 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Spiral binding', 'Hard binding', 'Home delivery'],
      },
    ],
  },
  {
    category: {
      name: 'Waste Management & Recycling',
      description:
        'Eco-friendly waste collection and recycling services. Sell your waste and add money to your wallet for booking other services.',
      icon: '♻️',
      featured: true,
      displayOrder: 9,
    },
    subServices: [
      {
        name: 'Plastic Waste Collection',
        description: 'Collect and recycle plastic waste',
        priceRange: { min: 5, max: 50 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Earn wallet credits', 'Doorstep pickup', 'Eco-friendly'],
        popular: true,
      },
      {
        name: 'Electronic Waste Collection',
        description: 'Collect e-waste and earn credits',
        priceRange: { min: 50, max: 5000 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
        features: ['Safe disposal', 'Earn credits', 'Free pickup'],
        popular: true,
      },
      {
        name: 'Metal Waste Collection',
        description: 'Sell metal scrap and earn credits',
        priceRange: { min: 10, max: 100 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Paper & Book Waste Collection',
        description: 'Collect old papers and books',
        priceRange: { min: 5, max: 30 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Glass Waste Collection',
        description: 'Collect and recycle glass waste',
        priceRange: { min: 5, max: 50 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
      {
        name: 'Rubber Waste Collection',
        description: 'Collect rubber and tyre waste',
        priceRange: { min: 10, max: 100 },
        priceType: 'per-item',
        estimatedDuration: { value: 2, unit: 'hours' },
      },
    ],
  },
];

module.exports = servicesData;
